

// surahData.js
export const surahs = [
  { name: "Al-Fatihah", meaning: "The Opening", verses: 7, city: "Makkah" },
  { name: "Al-Baqarah", meaning: "The Cow", verses: 286, city: "Madinah" },
  { name: "Aal-E-Imran", meaning: "The Family of Imran", verses: 200, city: "Madinah" },
  { name: "An-Nisa", meaning: "The Women", verses: 176, city: "Madinah" },
  { name: "Al-Ma'idah", meaning: "The Table Spread", verses: 120, city: "Madinah" },
  { name: "Al-An'am", meaning: "The Cattle", verses: 165, city: "Makkah" },
  { name: "Al-A'raf", meaning: "The Heights", verses: 206, city: "Makkah" },
  { name: "Al-Anfal", meaning: "The Spoils of War", verses: 75, city: "Madinah" },
  { name: "At-Tawbah", meaning: "The Repentance", verses: 129, city: "Madinah" },
  { name: "Yunus", meaning: "Jonah", verses: 109, city: "Makkah" },
  { name: "Hud", meaning: "Hud", verses: 123, city: "Makkah" },
  { name: "Yusuf", meaning: "Joseph", verses: 111, city: "Makkah" },
  { name: "Ar-Ra'd", meaning: "The Thunder", verses: 43, city: "Madinah" },
  { name: "Ibrahim", meaning: "Abraham", verses: 52, city: "Makkah" },
  { name: "Al-Hijr", meaning: "The Rocky Tract", verses: 99, city: "Makkah" },
  { name: "An-Nahl", meaning: "The Bee", verses: 128, city: "Makkah" },
  { name: "Al-Isra", meaning: "The Night Journey", verses: 111, city: "Makkah" },
  { name: "Al-Kahf", meaning: "The Cave", verses: 110, city: "Makkah" },
  { name: "Maryam", meaning: "Mary", verses: 98, city: "Makkah" },
  { name: "Ta-Ha", meaning: "Ta-Ha", verses: 135, city: "Makkah" },
  { name: "Al-Anbiya", meaning: "The Prophets", verses: 112, city: "Makkah" },
  { name: "Al-Hajj", meaning: "The Pilgrimage", verses: 78, city: "Madinah" },
  { name: "Al-Mu'minun", meaning: "The Believers", verses: 118, city: "Makkah" },
  { name: "An-Nur", meaning: "The Light", verses: 64, city: "Madinah" },
  { name: "Al-Furqan", meaning: "The Criterion", verses: 77, city: "Makkah" },
  { name: "Ash-Shu'ara", meaning: "The Poets", verses: 227, city: "Makkah" },
  { name: "An-Naml", meaning: "The Ant", verses: 93, city: "Makkah" },
  { name: "Al-Qasas", meaning: "The Stories", verses: 88, city: "Makkah" },
  { name: "Al-Ankabut", meaning: "The Spider", verses: 69, city: "Makkah" },
  { name: "Ar-Rum", meaning: "The Romans", verses: 60, city: "Makkah" },
  { name: "Luqman", meaning: "Luqman", verses: 34, city: "Makkah" },
  { name: "As-Sajdah", meaning: "The Prostration", verses: 30, city: "Makkah" },
  { name: "Al-Ahzab", meaning: "The Combined Forces", verses: 73, city: "Madinah" },
  { name: "Saba", meaning: "Sheba", verses: 54, city: "Makkah" },
  { name: "Fatir", meaning: "The Originator", verses: 45, city: "Makkah" },
  { name: "Ya-Sin", meaning: "Ya-Sin", verses: 83, city: "Makkah" },
  { name: "As-Saffat", meaning: "Those Who Set The Ranks", verses: 182, city: "Makkah" },
  { name: "Sad", meaning: "The Letter Sad", verses: 88, city: "Makkah" },
  { name: "Az-Zumar", meaning: "The Troops", verses: 75, city: "Makkah" },
  { name: "Ghafir", meaning: "The Forgiver", verses: 85, city: "Makkah" },
  { name: "Fussilat", meaning: "Explained In Detail", verses: 54, city: "Makkah" },
  { name: "Ash-Shura", meaning: "The Consultation", verses: 53, city: "Makkah" },
  { name: "Az-Zukhruf", meaning: "The Ornaments Of Gold", verses: 89, city: "Makkah" },
  { name: "Ad-Dukhan", meaning: "The Smoke", verses: 59, city: "Makkah" },
  { name: "Al-Jathiyah", meaning: "The Crouching", verses: 37, city: "Makkah" },
  { name: "Al-Ahqaf", meaning: "The Wind-Curved Sandhills", verses: 35, city: "Makkah" },
  { name: "Muhammad", meaning: "Muhammad", verses: 38, city: "Madinah" },
  { name: "Al-Fath", meaning: "The Victory", verses: 29, city: "Madinah" },
  { name: "Al-Hujurat", meaning: "The Rooms", verses: 18, city: "Madinah" },
  { name: "Qaf", meaning: "The Letter Qaf", verses: 45, city: "Makkah" },
  { name: "Adh-Dhariyat", meaning: "The Winnowing Winds", verses: 60, city: "Makkah" },
  { name: "At-Tur", meaning: "The Mount", verses: 49, city: "Makkah" },
  { name: "An-Najm", meaning: "The Star", verses: 62, city: "Makkah" },
  { name: "Al-Qamar", meaning: "The Moon", verses: 55, city: "Makkah" },
  { name: "Ar-Rahman", meaning: "The Beneficent", verses: 78, city: "Madinah" },
  { name: "Al-Waqi'ah", meaning: "The Inevitable", verses: 96, city: "Makkah" },
  { name: "Al-Hadid", meaning: "The Iron", verses: 29, city: "Madinah" },
  { name: "Al-Mujadilah", meaning: "The Pleading Woman", verses: 22, city: "Madinah" },
  { name: "Al-Hashr", meaning: "The Exile", verses: 24, city: "Madinah" },
  { name: "Al-Mumtahanah", meaning: "She That Is To Be Examined", verses: 13, city: "Madinah" },
  { name: "As-Saf", meaning: "The Ranks", verses: 14, city: "Madinah" },
  { name: "Al-Jumu'ah", meaning: "The Congregation, Friday", verses: 11, city: "Madinah" },
  { name: "Al-Munafiqun", meaning: "The Hypocrites", verses: 11, city: "Madinah" },
  { name: "At-Taghabun", meaning: "The Mutual Disillusion", verses: 18, city: "Madinah" },
  { name: "At-Talaq", meaning: "The Divorce", verses: 12, city: "Madinah" },
  { name: "At-Tahrim", meaning: "The Prohibition", verses: 12, city: "Madinah" },
  { name: "Al-Mulk", meaning: "The Sovereignty", verses: 30, city: "Makkah" },
  { name: "Al-Qalam", meaning: "The Pen", verses: 52, city: "Makkah" },
  { name: "Al-Haqqah", meaning: "The Reality", verses: 52, city: "Makkah" },
  { name: "Al-Ma'arij", meaning: "The Ascending Stairways", verses: 44, city: "Makkah" },
  { name: "Nuh", meaning: "Noah", verses: 28, city: "Makkah" },
  { name: "Al-Jinn", meaning: "The Jinn", verses: 28, city: "Makkah" },
  { name: "Al-Muzzammil", meaning: "The Enshrouded One", verses: 20, city: "Makkah" },
  { name: "Al-Muddaththir", meaning: "The Cloaked One", verses: 56, city: "Makkah" },
  { name: "Al-Qiyamah", meaning: "The Resurrection", verses: 40, city: "Makkah" },
  { name: "Al-Insan", meaning: "The Man", verses: 31, city: "Madinah" },
  { name: "Al-Mursalat", meaning: "The Emissaries", verses: 50, city: "Makkah" },
  { name: "An-Naba", meaning: "The Tidings", verses: 40, city: "Makkah" },
  { name: "An-Nazi'at", meaning: "Those Who Drag Forth", verses: 46, city: "Makkah" },
  { name: "Abasa", meaning: "He Frowned", verses: 42, city: "Makkah" },
  { name: "At-Takwir", meaning: "The Overthrowing", verses: 29, city: "Makkah" },
  { name: "Al-Infitar", meaning: "The Cleaving", verses: 19, city: "Makkah" },
  { name: "Al-Mutaffifin", meaning: "The Defrauding", verses: 36, city: "Makkah" },
  { name: "Al-Inshiqaq", meaning: "The Sundering", verses: 25, city: "Makkah" },
  { name: "Al-Buruj", meaning: "The Mansions Of The Stars", verses: 22, city: "Makkah" },
  { name: "At-Tariq", meaning: "The Nightcomer", verses: 17, city: "Makkah" },
  { name: "Al-A'la", meaning: "The Most High", verses: 19, city: "Makkah" },
  { name: "Al-Ghashiyah", meaning: "The Overwhelming", verses: 26, city: "Makkah" },
  { name: "Al-Fajr", meaning: "The Dawn", verses: 30, city: "Makkah" },
  { name: "Al-Balad", meaning: "The City", verses: 20, city: "Makkah" },
  { name: "Ash-Shams", meaning: "The Sun", verses: 15, city: "Makkah" },
  { name: "Al-Layl", meaning: "The Night", verses: 21, city: "Makkah" },
  { name: "Ad-Duha", meaning: "The Morning Hours", verses: 11, city: "Makkah" },
  { name: "Ash-Sharh", meaning: "The Relief", verses: 8, city: "Makkah" },
  { name: "At-Tin", meaning: "The Fig", verses: 8, city: "Makkah" },
  { name: "Al-Alaq", meaning: "The Clot", verses: 19, city: "Makkah" },
  { name: "Al-Qadr", meaning: "The Power", verses: 5, city: "Makkah" },
  { name: "Al-Bayyinah", meaning: "The Clear Proof", verses: 8, city: "Makkah" },
  { name: "Az-Zalzalah", meaning: "The Earthquake", verses: 8, city: "Makkah" },
  { name: "Al-Adiyat", meaning: "The Chargers", verses: 11, city: "Makkah" },
  { name: "Al-Qari'ah", meaning: "The Calamity", verses: 11, city: "Makkah" },
  { name: "At-Takathur", meaning: "The Rivalry In World Increase", verses: 8, city: "Makkah" },
  { name: "Al-Asr", meaning: "The Declining Day", verses: 3, city: "Makkah" },
  { name: "Al-Humazah", meaning: "The Traducer", verses: 9, city: "Makkah" },
  { name: "Al-Fil", meaning: "The Elephant", verses: 5, city: "Makkah" },
  { name: "Quraysh", meaning: "Quraysh", verses: 4, city: "Makkah" },
  { name: "Al-Ma'un", meaning: "The Small Kindnesses", verses: 7, city: "Makkah" },
  { name: "Al-Kawthar", meaning: "The Abundance", verses: 3, city: "Makkah" },
  { name: "Al-Kafirun", meaning: "The Disbelievers", verses: 6, city: "Makkah" },
  { name: "An-Nasr", meaning: "The Divine Support", verses: 3, city: "Madinah" },
  { name: "Al-Masad", meaning: "The Palm Fiber", verses: 5, city: "Makkah" },
  { name: "Al-Ikhlas", meaning: "The Sincerity", verses: 4, city: "Makkah" },
  { name: "Al-Falaq", meaning: "The Daybreak", verses: 5, city: "Makkah" },
  { name: "An-Nas", meaning: "The Mankind", verses: 6, city: "Makkah" }
];



